### ISSUE TITLE
How to remove autoconfig

### ISSUE THREAD

**Issue by lackomacko74** [UltimateByte/plesk_mail_autoconfig#3]
We use plesk server for hosting a lot of domains.
Some domain's mail hosted by Office365, and the rest hosted on our Plesk server.
Where the mail hosting is on O365, the autoconfig result a problem because the autodiscover default redirection....
Could you help me, how can switch off the autoconfig on the O365 mail hosted domains?

**Comment by UltimateByte** [comment]
Hey, very good question !
We had the issue as well with some customers and found a solution, I'll try to get in touch this morning with the solution. I shall write a FAQ as well.

**Comment by UltimateByte** [comment]
OK, so the fix is quite easy in the end : 
Add this to the given domain's Apache configuration (can do this from within Plesk):

```
Alias "/autodiscover" "/var/www/vhosts/DOMAIN.TLD/httpdocs/autodiscover"
Alias "/Autodiscover" "/var/www/vhosts/DOMAIN.TLD/httpdocs/autodiscover"
```

(replace domain.tld with the actual domain).
You can also add an autodiscover.xml and Autodiscover.xml to the actual directory from the domain if you wish to add a custom autodiscover file.

Thank you

**Comment by UltimateByte** [comment]
This is now added to the freshly created wiki.
https://github.com/UltimateByte/plesk_mail_autoconfig/wiki/FAQ#what-if-i-want-to-disable-autoconfig-for-one-domain-only
